"""記事モデルログモデル拡張

Revision ID: 030c4b6780cc
Revises: 1a9096e00ac9
Create Date: 2025-04-04 14:30:20.224796

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '030c4b6780cc'
down_revision = '1a9096e00ac9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('site_id', sa.Integer(), nullable=False),
    sa.Column('step', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['site_id'], ['site.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('article', schema=None) as batch_op:
        batch_op.add_column(sa.Column('genre', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('preview_html', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('posted_time', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('gpt_tokens', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('gpt_cost_usd', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('article', schema=None) as batch_op:
        batch_op.drop_column('gpt_cost_usd')
        batch_op.drop_column('gpt_tokens')
        batch_op.drop_column('posted_time')
        batch_op.drop_column('preview_html')
        batch_op.drop_column('genre')

    op.drop_table('post_log')
    # ### end Alembic commands ###
