"""PostLog統合モデル初期化

Revision ID: a6a369a487fc
Revises: 
Create Date: 2025-04-04 19:35:30.437879

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a6a369a487fc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post_log', schema=None) as batch_op:
        batch_op.add_column(sa.Column('article_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('genre', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('keyword', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('title', sa.String(length=300), nullable=True))
        batch_op.add_column(sa.Column('preview_html', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('gpt_tokens', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('gpt_cost_usd', sa.Float(), nullable=True))
        batch_op.alter_column('site_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.create_foreign_key(None, 'article', ['article_id'], ['id'])
        batch_op.drop_column('status')
        batch_op.drop_column('message')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post_log', schema=None) as batch_op:
        batch_op.add_column(sa.Column('message', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('site_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('gpt_cost_usd')
        batch_op.drop_column('gpt_tokens')
        batch_op.drop_column('preview_html')
        batch_op.drop_column('title')
        batch_op.drop_column('keyword')
        batch_op.drop_column('genre')
        batch_op.drop_column('article_id')

    # ### end Alembic commands ###
